"""CLAUDE.md generator: composes dynamic CLAUDE.md from phase, plugins, and context."""

from __future__ import annotations

# Phase instruction templates
_PHASE_INSTRUCTIONS: dict[str, str] = {
    "research": """## RESEARCH PHASE

You are in the Research phase. Your goal is to deeply understand the problem domain,
explore existing solutions, and identify constraints before designing a solution.

### Deliverables
- Problem statement document
- Domain research findings
- Constraints and requirements list
""",
    "analysis": """## ANALYSIS PHASE

You are in the Analysis phase. Design the solution architecture, make technology
decisions, and document them as Architecture Decision Records (ADRs).

### Deliverables
- Solution design document
- Architecture Decision Records (ADRs)
- Technology stack rationale
""",
    "plan": """## PLAN PHASE

You are in the Plan phase. Break the solution into implementable features with
clear acceptance criteria, estimate complexity, and compute implementation waves.

### Deliverables
- Feature specifications (XML format)
- Dependency graph
- Implementation wave plan
""",
    "implement": """## IMPLEMENT PHASE

You are in the Implement phase. Build features incrementally, one acceptance
criterion at a time. Write real tests (no mocks). Commit after each criterion passes.

### Rules
- One acceptance criterion at a time
- Real tests against real services/emulators
- Commit with descriptive messages after each criterion
- Update feature-progress.json after each step
""",
    "deploy": """## DEPLOY PHASE

You are in the Deploy phase. Deploy the application, run smoke tests,
and verify the deployment meets acceptance criteria.

### Deliverables
- Deployment configuration
- Smoke test results
- Deployment verification report
""",
    "sustain": """## SUSTAIN PHASE

You are in the Sustain phase. Set up monitoring, alerting, and operational
runbooks. Address any post-deployment issues.

### Deliverables
- Monitoring configuration
- Alerting rules
- Operational runbook
""",
}

_HEADER = """# CLAUDE.md — RAPIDS Orchestration Context
# Auto-generated by rapids-core. Do not edit manually.
"""

_MAX_LINES = 200


def generate_claude_md(
    config: dict,
    plugin_overlays: dict[str, str] | None = None,
) -> str:
    """Generate a CLAUDE.md file from the current RAPIDS state.

    Args:
        config: Dict with keys:
            - phase: str - Current phase name
            - tier: int - Scope tier
            - plugins: list[str] - Active plugin names
            - accumulated_context: dict - Key decisions, constraints, etc. (optional)
            - project_id: str - Project identifier (optional)
        plugin_overlays: Dict mapping plugin name to overlay content string.

    Returns:
        Generated CLAUDE.md content string, kept under 200 lines.
    """
    if plugin_overlays is None:
        plugin_overlays = {}

    phase = config.get("phase", "implement")
    tier = config.get("tier", 1)
    plugins = config.get("plugins", [])
    context = config.get("accumulated_context", {})
    project_id = config.get("project_id", "unknown")

    sections: list[str] = [_HEADER]

    # Project context
    sections.append(f"**Project:** {project_id} | **Tier:** {tier} | **Phase:** {phase}\n")

    # Phase instructions
    phase_instructions = _PHASE_INSTRUCTIONS.get(phase, "")
    if phase_instructions:
        sections.append(phase_instructions)

    # Accumulated context (key decisions, constraints)
    if context:
        context_lines = ["## Accumulated Context\n"]
        key_decisions = context.get("key_decisions", [])
        if key_decisions:
            context_lines.append("### Key Decisions")
            for decision in key_decisions:
                context_lines.append(f"- {decision}")
            context_lines.append("")

        constraints = context.get("constraints", [])
        if constraints:
            context_lines.append("### Constraints")
            for constraint in constraints:
                context_lines.append(f"- {constraint}")
            context_lines.append("")

        sections.append("\n".join(context_lines))

    # Plugin overlays
    if plugins and plugin_overlays:
        overlay_lines = ["## Plugin Guidance\n"]
        for plugin_name in plugins:
            overlay = plugin_overlays.get(plugin_name, "")
            if overlay:
                overlay_lines.append(f"### {plugin_name}\n")
                overlay_lines.append(overlay.strip())
                overlay_lines.append("")
        if len(overlay_lines) > 1:
            sections.append("\n".join(overlay_lines))

    result = "\n".join(sections)

    # Enforce line limit by truncating plugin overlays if needed
    lines = result.split("\n")
    if len(lines) > _MAX_LINES:
        lines = lines[:_MAX_LINES]
        lines.append("\n<!-- Truncated to 200 lines -->")
        result = "\n".join(lines)

    return result
