"""CLAUDE.md generator: composes dynamic CLAUDE.md from phase, plugins, and context."""

from __future__ import annotations

# Phase instruction templates
_PHASE_INSTRUCTIONS: dict[str, str] = {
    "research": """## RESEARCH PHASE

You are in the Research phase. Your goal is to deeply understand the problem domain,
explore existing solutions, and identify constraints before designing a solution.

### Deliverables
- Problem statement document
- Domain research findings
- Constraints and requirements list
""",
    "analysis": """## ANALYSIS PHASE

You are in the Analysis phase. Design the solution architecture, make technology
decisions, and document them as Architecture Decision Records (ADRs).

### Deliverables
- Solution design document
- Architecture Decision Records (ADRs)
- Technology stack rationale
""",
    "plan": """## PLAN PHASE

You are in the Plan phase. Break the solution into implementable features with
clear acceptance criteria, estimate complexity, and compute implementation waves.

### Deliverables
- Feature specifications (XML format)
- Dependency graph
- Implementation wave plan
""",
    "implement": """## IMPLEMENT PHASE

You are in the Implement phase. Build features incrementally, one acceptance
criterion at a time. Write real tests (no mocks). Commit after each criterion passes.

### Rules
- One acceptance criterion at a time
- Real tests against real services/emulators
- Commit with descriptive messages after each criterion
- Update feature-progress.json after each step
""",
    "deploy": """## DEPLOY PHASE

You are in the Deploy phase. Deploy the application, run smoke tests,
and verify the deployment meets acceptance criteria.

### Deliverables
- Deployment configuration
- Smoke test results
- Deployment verification report
""",
    "sustain": """## SUSTAIN PHASE

You are in the Sustain phase. Set up monitoring, alerting, and operational
runbooks. Address any post-deployment issues.

### Deliverables
- Monitoring configuration
- Alerting rules
- Operational runbook
""",
}

_HEADER = """# CLAUDE.md — RAPIDS Orchestration Context
# Auto-generated by rapids-core. Do not edit manually.
"""

_MAX_LINES = 200


def generate_claude_md(
    config: dict,
    plugin_overlays: dict[str, str] | None = None,
    work_item: dict | None = None,
    other_work_items: list[dict] | None = None,
) -> str:
    """Generate a CLAUDE.md file from the current RAPIDS state.

    Args:
        config: Dict with keys:
            - phase: str - Current phase name
            - tier: int - Scope tier
            - plugins: list[str] - Active plugin names
            - accumulated_context: dict - Key decisions, constraints, etc. (optional)
            - project_id: str - Project identifier (optional)
        plugin_overlays: Dict mapping plugin name to overlay content string.
        work_item: Optional active work item dict. If provided, phase/tier
            are taken from the work item instead of the config.
        other_work_items: Optional list of other active work item dicts
            to show in the context section.

    Returns:
        Generated CLAUDE.md content string, kept under 200 lines.
    """
    if plugin_overlays is None:
        plugin_overlays = {}

    # If a work item is provided, use its phase/tier instead of config-level
    if work_item:
        phase = work_item.get("current_phase", config.get("phase", "implement"))
        tier = work_item.get("tier", config.get("tier", 1))
    else:
        phase = config.get("phase", "implement")
        tier = config.get("tier", 1)

    plugins = config.get("plugins", [])
    context = config.get("accumulated_context", {})
    project_id = config.get("project_id", "unknown")

    sections: list[str] = [_HEADER]

    # Project and work item context
    if work_item:
        wi_id = work_item.get("id", "?")
        wi_title = work_item.get("title", "")
        wi_type = work_item.get("type", "?")
        sections.append(
            f"**Project:** {project_id} | **Work Item:** {wi_id} ({wi_type}) "
            f"| **Tier:** {tier} | **Phase:** {phase}\n"
        )
        if wi_title:
            sections.append(f"**Task:** {wi_title}\n")
    else:
        sections.append(f"**Project:** {project_id} | **Tier:** {tier} | **Phase:** {phase}\n")

    # Phase instructions
    phase_instructions = _PHASE_INSTRUCTIONS.get(phase, "")
    if phase_instructions:
        sections.append(phase_instructions)

    # Accumulated context (key decisions, constraints)
    if context:
        context_lines = ["## Accumulated Context\n"]
        key_decisions = context.get("key_decisions", [])
        if key_decisions:
            context_lines.append("### Key Decisions")
            for decision in key_decisions:
                context_lines.append(f"- {decision}")
            context_lines.append("")

        constraints = context.get("constraints", [])
        if constraints:
            context_lines.append("### Constraints")
            for constraint in constraints:
                context_lines.append(f"- {constraint}")
            context_lines.append("")

        sections.append("\n".join(context_lines))

    # Activity checklist for current phase
    activities = config.get("activities")
    activity_progress = config.get("activity_progress")
    if activities:
        from rapids_core.activity_manager import format_activity_checklist
        sections.append(f"## Activities for {phase.capitalize()} Phase\n")
        sections.append(format_activity_checklist(activities, activity_progress))

    # Other active work items (so the agent knows what else is happening)
    if other_work_items:
        wi_lines = ["## Other Active Work Items\n"]
        for owi in other_work_items:
            owi_id = owi.get("id", "?")
            owi_title = owi.get("title", "")[:40]
            owi_type = owi.get("type", "?")
            owi_phase = owi.get("current_phase", "?")
            owi_tier = owi.get("tier", "?")
            wi_lines.append(f"- **{owi_id}** ({owi_type}, T{owi_tier}): {owi_title} — {owi_phase} phase")
        wi_lines.append("")
        sections.append("\n".join(wi_lines))

    # Plugin overlays
    if plugins and plugin_overlays:
        overlay_lines = ["## Plugin Guidance\n"]
        for plugin_name in plugins:
            overlay = plugin_overlays.get(plugin_name, "")
            if overlay:
                overlay_lines.append(f"### {plugin_name}\n")
                overlay_lines.append(overlay.strip())
                overlay_lines.append("")
        if len(overlay_lines) > 1:
            sections.append("\n".join(overlay_lines))

    result = "\n".join(sections)

    # Enforce line limit by truncating plugin overlays if needed
    lines = result.split("\n")
    if len(lines) > _MAX_LINES:
        lines = lines[:_MAX_LINES]
        lines.append("\n<!-- Truncated to 200 lines -->")
        result = "\n".join(lines)

    return result
